# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 22:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('client_name', models.CharField(blank=True, max_length=30)),
                ('client_description', models.CharField(blank=True, max_length=200)),
                ('client_site', models.CharField(blank=True, max_length=100)),
                ('candidate_JD', models.FileField(db_index=True, upload_to='static/upload/recruiter/JD/')),
                ('new_flag', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('new_flag',),
            },
        ),
        migrations.CreateModel(
            name='Candidateinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=30)),
                ('lastname', models.CharField(blank=True, max_length=30)),
                ('skills', models.TextField(blank=True)),
                ('social_linkedin', models.TextField(blank=True, max_length=30)),
                ('candidate_resume', models.FileField(db_index=True, upload_to='static/upload/recruiter/resume')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpotWrkApp.Candidate')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(blank=True, max_length=30)),
                ('skill', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('candidate_experience', models.CharField(blank=True, max_length=30)),
                ('candidate_number', models.IntegerField(default=1)),
                ('company_number', models.IntegerField(default=0)),
                ('hired_count', models.IntegerField(default=0)),
                ('new_flag', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('address1', models.CharField(blank=True, max_length=30)),
                ('address2', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('state', models.CharField(blank=True, max_length=30)),
                ('zipcode', models.CharField(blank=True, max_length=30)),
                ('pay_pal_cardnumber', models.CharField(blank=True, default='', max_length=30)),
                ('pay_pal_code', models.CharField(blank=True, default='', max_length=30)),
                ('pay_pal_valid', models.CharField(blank=True, default='', max_length=30)),
                ('pay_pal_nameoncard', models.CharField(blank=True, default='', max_length=30)),
                ('pay_credit_cardnumber', models.CharField(blank=True, default='', max_length=30)),
                ('pay_credit_code', models.CharField(blank=True, default='', max_length=30)),
                ('pay_credit_valid', models.CharField(blank=True, default='', max_length=30)),
                ('pay_credit_nameoncard', models.CharField(blank=True, default='', max_length=30)),
                ('pay_debit_cardnumber', models.CharField(blank=True, default='', max_length=30)),
                ('pay_debit_code', models.CharField(blank=True, default='', max_length=30)),
                ('pay_debit_valid', models.CharField(blank=True, default='', max_length=30)),
                ('pay_debit_nameoncard', models.CharField(blank=True, default='', max_length=30)),
                ('invitecode', models.CharField(blank=True, default='', max_length=30)),
                ('invite_friend', models.CharField(blank=True, default='', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('first_name',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('is_completed', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('skill', models.TextField(blank=True)),
                ('is_company', models.BooleanField(default=False)),
                ('company_name', models.CharField(blank=True, max_length=30)),
                ('current_role', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='static/upload/')),
                ('social_linkedin', models.CharField(blank=True, max_length=30)),
                ('social_facebook', models.CharField(blank=True, max_length=30)),
                ('last_access', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tborder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=30)),
                ('industry', models.CharField(blank=True, max_length=30)),
                ('skill', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('experience', models.CharField(default='Mid level', max_length=30)),
                ('criteria', models.TextField(blank=True, default='None')),
                ('criteria_header', models.CharField(blank=True, default='None', max_length=30)),
                ('pay_mode', models.CharField(blank=True, max_length=30)),
                ('pay_type', models.CharField(blank=True, max_length=30)),
                ('pay_flatfee', models.IntegerField(default=300)),
                ('pay_fee_type', models.CharField(default='$', max_length=30)),
                ('turnaround', models.CharField(blank=True, max_length=30)),
                ('new_flag', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('new_flag',),
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpotWrkApp.Experience'),
        ),
    ]
