# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotWrkApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_JD',
            field=models.FileField(db_index=True, default='static/img/spotwrk/usericon.png', upload_to='static/upload/recruiter/JD/'),
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='candidate_resume',
            field=models.FileField(db_index=True, default='static/img/spotwrk/usericon.png', upload_to='static/upload/recruiter/resume'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='static/img/spotwrk/usericon.png', upload_to='static/upload/'),
        ),
    ]
