# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SpotWrkApp', '0001_initial'),
        ('employer', '0004_auto_20170924_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='eorder',
            name='recruiter_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SpotWrkApp.Tborder'),
        ),
    ]
