# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 13:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_eorder_recruiter_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eorder',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
