SOCIAL_AUTH_TWITTER_KEY = '2kgHxSU7FGLFZE1Q8afVQzd1W'
SOCIAL_AUTH_TWITTER_SECRET = 'cGoJwhHZwniDJ73aIcmMnnd9loLtv6gKY0Qfs7qffjBGOFUq5F'
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/home/'
SOCIAL_AUTH_LOGIN_URL = '/'